### ISSUE TITLE
[Enhancement] Fluid Visibility JEI

### ISSUE THREAD

**Issue by Freebi85** [HaydenBelanger/assemblylinemachines#12]
Hello :)
The fluid mixer can work with different liquids. Unfortunately, it is not always clear in JEI what exactly is needed. (Except to wait until the fluid-dots fill with a certain color^^).

A small fluidbar in JEI or something like that would be very helpful.

Cheers :)

**Comment by HaydenBelanger** [comment]
This will be in the next release of the mod for 1.18.
