### ISSUE TITLE
crash when placing a vacuum hopper on top of a experience mill(1.17-forge-37.1.0)

### ISSUE THREAD

**Issue by SDUBZ** [HaydenBelanger/assemblylinemachines#18]
Forge: 1.17-forge-37.1.0

assemblylinemachines-1.17.1-1.3

crash report:

[crash-2021-12-05_22.04.44-server.txt](https://github.com/HaydenBelanger/assemblylinemachines/files/7655737/crash-2021-12-05_22.04.44-server.txt

logs:

[debug.log](https://github.com/HaydenBelanger/assemblylinemachines/files/7655739/debug.log)
[latest.log](https://github.com/HaydenBelanger/assemblylinemachines/files/7655740/latest.log)
)

**Comment by HaydenBelanger** [comment]
Fixed in 1.3.0.1, on CurseForge.
