### ISSUE TITLE
assemblylinemachines-1.17.1-1.3.0.1.jar wont launch

### ISSUE THREAD

**Issue by SDUBZ** [HaydenBelanger/assemblylinemachines#20]
you compiled this version with java 16
so it doesnt launch

**Comment by SDUBZ** [comment]
als you are launching client events on the server side 
[latest.log](https://github.com/HaydenBelanger/assemblylinemachines/files/7661193/latest.log)

**Comment by HaydenBelanger** [comment]
Hi, I can definitely rollback the Java version I compile with. Also, what were you doing when the game crashed? Was it just during startup?

**Comment by HaydenBelanger** [comment]
Based on the log, it's startup, and I can't re-create the issue, I'm able to start and connect to the server perfectly fine. Do you have a debug.log?

**Comment by HaydenBelanger** [comment]
I've recompiled with Java 16 out of caution, so please let me know if 1.3.0.2 fixes whatever was happening. If it doesn't, I don't think it would be anything my mod is doing unfortunately.
