### ISSUE TITLE
Crash with Immersive engineering

### ISSUE THREAD

**Issue by freopt** [HaydenBelanger/assemblylinemachines#24]
I placed a IE creative capacitor next to the large battery from assemblyline to test some things, game crashed, world seems to be corrupted as well

https://gist.github.com/freopt/661296d25a203173099481e849fcf0f3

**Comment by HaydenBelanger** [comment]
Hi, you will either have to remove the battery cell using an external world editor or wait for a hotfix for this and a few other issues within the next 2 days.

**Comment by freopt** [comment]
it was a test superflat world so no problem
