### ISSUE TITLE
[1.18.1] error during the sided_setup event phase

### ISSUE THREAD

**Issue by Blaiin** [HaydenBelanger/assemblylinemachines#26]
Description:

Game crashes and report blaming Assembly Line Machines

Link: https://pastebin.com/hrRL3kHT

- assemblylinemachines-1.18-1.3.3
- Forge 39.0.8

**Comment by HaydenBelanger** [comment]
Does this bug happen to you when the mod is alone? I'm having quite a bit of trouble diagnosing this, and ConcurrentModificationExceptions are hard to hunt down.

**Comment by Blaiin** [comment]
I can test this and honestly i should have before reporting, mistake on my part,
I'll let you know here if the same issue comes up.

**Comment by HaydenBelanger** [comment]
I changed a line of code, and while I don't know if it'll help alleviate the issue, I believe it most likely will. So that will be in the next update :)
