### ISSUE TITLE
Balancing: Enery generation degraded from gearbox / crankmill to coal generator 

### ISSUE THREAD

**Issue by 7eggert** [HaydenBelanger/assemblylinemachines#28]
The gearbox will generate 60k RF with one charcoal
The coal generator will generate 6.4k RF with one charcoal

This seems like bad balancing, even the faster operation does not seem to be worth it.

**Comment by HaydenBelanger** [comment]
I'm hesitant to change the DEFAULT output, as I do believe it's balanced. The first option requires a Gearbox, Crankmill, and the Compatibility Upgrade, as well it will burn even if it cannot generate. The second only requires the Coal Generator, and will stop if it is full.

However, I get why you would want it changed, so I'll be adding a config option to the raw output in the next version.
