### ISSUE TITLE
1.18.1 [1.3.5] Refinery internal tank

### ISSUE THREAD

**Issue by hornertom** [HaydenBelanger/assemblylinemachines#30]
Hey, I was trying to do some graphene rods when i notice it requires 5 bukets of carbon, when i did the liquid carbon it wont start the recipe until all 5b are inserted, but the refinery only takes 4b, i tried with a tank underneath and doesnt work, tried to outut with pipes and nothing either. Is there a mechanic im missing or should the refinery tank be bigger?

**Comment by HaydenBelanger** [comment]
This was a foolish oversight, I'll make sure a fix is included in the next version.

**Comment by HaydenBelanger** [comment]
This will be fixed in the next version.
