### ISSUE TITLE
JEI enhancements/fixes

### ISSUE THREAD

**Issue by freopt** [HaydenBelanger/assemblylinemachines#31]
In JEI when looking at the grinding crafting type, the tooltip that shows what mod an item is from is not there

![image](https://user-images.githubusercontent.com/45438411/148659596-c6919985-20dd-4723-8c67-bda33f1ce11f.png)

vs literally any other recipe type

![image](https://user-images.githubusercontent.com/45438411/148659664-85efa6df-ee01-48f8-acf4-078ab0cafa96.png)

also a request is to switch the machine used from being an ingredient in JEI to the way other mods do it
![image](https://user-images.githubusercontent.com/45438411/148659750-ded7e26f-5850-4b19-b710-f5b44f9fc64e.png)

and add the electric furnace as a smelter so it shows up in the list

**Comment by HaydenBelanger** [comment]
Hi there, I've tried in both 1.18 and 1.18.1, and I can't reproduce the thumbnail bug you showed me. I'd take a look at your JEI options.
![Capture](https://user-images.githubusercontent.com/7004666/148667904-88680170-16d3-42bb-bbd2-1d8b651fa5ce.PNG)
As for the change to where the machine is placed, I'll see what I can do about that.

**Comment by HaydenBelanger** [comment]
For the next version, I can switch the location of the machine within the GUI to the more typical one for most of my machines with a few notable exceptions, including the Grinder. Right now, it will need to stay as an "ingredient" within the GUI.
