### ISSUE TITLE
Editable parameters on Simple Machines.

### ISSUE THREAD

**Issue by freopt** [HaydenBelanger/assemblylinemachines#32]
Tested multiple recipes, none worked. Using the exact same setup for recipes that use water does work

also personal opinion but it takes way too many clicks to crank machines, especially when the fluid bath and grinder are much much faster

**Comment by HaydenBelanger** [comment]
I've tried several recipes and in both 1.18 and 1.18.1 and I unfortunately can't reproduce this. However, I will see about adding in a config option to change the default ability of the Simple Machines.

**Comment by HaydenBelanger** [comment]
Will be available in next version to change the efficacy of the Simple Machines.
