### ISSUE TITLE
Refineries (and other machines) should reject wrong liquids; omnicables should only insert energy; Pipes need filters

### ISSUE THREAD

**Issue by 7eggert** [HaydenBelanger/assemblylinemachines#35]
assemblylinemachines-1.18-1.3.6.jar

I set up some refineries using advanced omnipipes and found that they are set by default to insert fluid/items/energy. Thus the oil got inserted into all the refineries and into the fluid crafting, too. After the oil was empty the pump(?) put two buckets of lava into the refineries, too.

My ¢¢:
* The machines should only accept fluids that they can use.
* Pipes should not insert fluids/items by default.
* Advanced pipes need a way to filter fluids, too. (Maybe the fluid router is meant to do that but it's not obvious how it's to be used).

**Comment by HaydenBelanger** [comment]
If you place a filled Bucket/other fluid-storing modded container into the item slots within the Advanced Fluid Pipe GUI, it will filter according to the contained fluid. As for the other ¢, I will add a config option to allow the default input state on pipes to be set for the next version.
