### ISSUE TITLE
Crash with Starlight [1.18.1]

### ISSUE THREAD

**Issue by Blatts12** [HaydenBelanger/assemblylinemachines#45]
Loaded Mods:
- Starlight 1.0.1
- ALM 1.3.8
- Forge 39.0.64

[debug.log](https://github.com/HaydenBelanger/assemblylinemachines/files/7989276/debug.log)
[crash.log](https://github.com/HaydenBelanger/assemblylinemachines/files/7989281/crash-2022-02-02_19.38.38-client.txt)

Edit: No crash with OneProbe installed

**Comment by HaydenBelanger** [comment]
I did exactly the setup you described and I can't reproduce. I'm sorry.

**Comment by Blatts12** [comment]
I tested it again:
Starlight 1.0.0 - no crash
Starlight 1.0.1 - crash

Unfortunately I need to use 1.0.1 because it's compatible with Create.
