### ISSUE TITLE
Quantum Link Crash

### ISSUE THREAD

**Issue by grundyboy34** [HaydenBelanger/assemblylinemachines#49]
Experienced a crash when clicking the green checkmark on the Quantum Link UI.

https://pastebin.com/MdiH2vzM

**Comment by HaydenBelanger** [comment]
I'll have a patch in the next version.

**Comment by TheDarkPreacher** [comment]
Had the same issue. Placed Quantum Link, opened UI, clicked green checkmark, game crashed.
https://bytebin.lucko.me/pwiw4CMe5N
