### ISSUE TITLE
Condensed Void / Corrupted Shards

### ISSUE THREAD

**Issue by gawamaster** [HaydenBelanger/assemblylinemachines#51]
It won't allow condensed void to be poured onto ground from void buckets in order to throw Nether Star shards into it to get Corrupted shards so we can power the Entropy Reactor.  There is a picture of condensed void in the over world on the ground and another picture of condensed void enclosed in glass but we cannot figure out how to pour the condensed void out of the bucket.

**Comment by HaydenBelanger** [comment]
What version are you using and what is the bucket doing when you use it against the ground?

**Comment by gawamaster** [comment]
Hi Hayden,
Thank you for your quick response.
The bucket doesn’t pour out at all.  I tried pouring it on different blocks, down mountains, on glass, and even in the end but nothing happens.  I was able to finally get the Condensed Void on glass by using the mod ‘Refined Storage’.  That mod has a block that allows fluids to pour onto the ground.
The group of people I am playing with really love the mod; although, when we get stuck, there isn’t much on the internet to assist (which can be a good thing since it forces us to put our heads together to come up with solutions).  But, it is turning out to be one of our favorite mods.
We are playing Another Quality Modpack 3 (Forge).
Thanks again and Kind Regards,
Jason

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by HaydenBelanger** [comment]
Hello! A member of your party (or perhaps you), waycooljunior, has posted to the Curseforge that it was a configuration issue with AQM3, so I'm glad to say it looks like you got everything worked out so I'm going to close this for now. :)
