### ISSUE TITLE
Refinery and Omnipipe no way to whitelist gases

### ISSUE THREAD

**Issue by gawamaster** [HaydenBelanger/assemblylinemachines#52]
I am not sure if it is working as designed.  We have oil going into a refinery and it produces 2 gases: Propane and Ethane.  We are trying to whitelist where propane goes out the left side and Ethane goes out the right side but there isn't a way to whitelist gases.  When we try to pick up gas in bucket it doesn't work.  We tried using Refined Storage with fluid drive and we can get the gases into the refined storage system but we back to original issue that we can't figure out how to whitelist the gases.  Please help since we are now stuck.  Thanks Much!

**Comment by HaydenBelanger** [comment]
Hi, try using a Fluid Router to split off where you want the gases to go when leaving the Refinery; they're designed to be intentionally difficult to work with but a Fluid Router will be able to divide like what you want.
