### ISSUE TITLE
Electric purifier/grinder* issues

### ISSUE THREAD

**Issue by CloWnicide** [HaydenBelanger/assemblylinemachines#53]
So on the latest version - 1.18.2-1.4 - the purifier no longer accepts any input items as well as the smelter not processing any items that I pipe into it.

**Comment by HaydenBelanger** [comment]
Hello! With the Purifier in 1.4, you must put in the primary item (ie. not the Sand or Gravel) first before the other slots will accept - to help with automation.

As for the other situation, 
![2022-04-25_15 33 52](https://user-images.githubusercontent.com/7004666/165178787-1f60a316-fdcf-4ecf-8725-958a54725766.png)
I wasn't able to reproduce the issues with the Furnace - it seems like it's working the way it's intended to.

**Comment by CloWnicide** [comment]
Correction: The electric grinder is the issue.

![2022-04-25_18 10 53](https://user-images.githubusercontent.com/27911500/165199145-7620ee21-8e42-4427-9626-e16e06d82887.png)
![2022-04-25_18 10 56](https://user-images.githubusercontent.com/27911500/165199153-86aa349e-2aed-4a02-8296-08afe64f6eaf.png)

**Comment by HaydenBelanger** [comment]
Hi! I understand but I'm still having a fair bit of trouble reproducing this issue. What modpack and version are you using so I can diagnose exactly what's wrong?

**Comment by HaydenBelanger** [comment]
Hi again, if you have Cooking for Blockheads 12.0.0 and Balm 3.0.2+0 in your pack you're playing with, it's been determined this causes compat issues in recent versions - see #55 for more info, but try updating to 12.0.1/3.0.3+0 and the issue should hopefully be gone.

**Comment by CloWnicide** [comment]
Currently using 12.0.1 of CFBH and 3.0.3+0 for Balm already..
