### ISSUE TITLE
Cannot grind ores or ingots with manual grinder

### ISSUE THREAD

**Issue by TheDarkPreacher** [HaydenBelanger/assemblylinemachines#55]
ALM Version: 1.18.2-1.4.1
Forge Version: 40.1.0

Summary of Bug: When attempting to grind ores/ingots (iron, copper, gold, etc.) with the manual grinder with any blade installed (titanium, gold, steel), it does nothing at all.

Expected behavior: right click ore/ingot on grinder, get ground material back.

Steps to reproduce: Start up a world with version 1.4.1, get an ore/ingot, make/get a manual grinder, install a blade, attempt to grind ore/ingot into ground version.

Additional Info: This feature worked in version 1.3.9, but after updating to 1.4.1, it is no longer working.

**Comment by TheDarkPreacher** [comment]
On a whim, I decided to attempt to fix the issue with a datapack, copied the JSON files for 1.3.9 to make a datapack for 1.4.1, and that fixed the issue. Seems that version 1.4.1 is still looking for the JSON files for 1.3.9 instead of the ones it has. My datapack is working for the manual grinder so far, have yet to see if it works with any of the higher tier grinders.

**Comment by HaydenBelanger** [comment]
Hi! That's strange that it's giving you so much trouble - there were a number of changes made between 1.3.9 and 1.4 but none that should impact grinding. Are you using a modpack at all?

**Comment by TheDarkPreacher** [comment]
I am, actually. ALM is the main tech mod I'm using in the pack I'm building, Seaside Logistics. But yeah, changing the JSON to the 1.3.9 version for the grinder recipes re-enabled them all. I noticed that the recipes for all the grinder recipes mostly use forge tags in 1.4.1. One of the mods in the pack is Cooking For Blockheads, and that has been making issues with Forge tags. I think that issue has been reported, and fixed for food items, but I didn't think it would effect _all_ forge tags.

**Comment by HaydenBelanger** [comment]
That explains why the 1.3.9 version works fine -- tagging for recipes are new. When the mod is alone, it functions well enough. Hopefully, CfB releases a patch soon that helps them play a bit nicer, but I know for some older mods, updating from 18.1 to 18.2 was hard due to the tag changes.
