### ISSUE TITLE
Recipes break when making a Kubejs script that removes a single recipe.

### ISSUE THREAD

**Issue by LoSilopante** [HaydenBelanger/assemblylinemachines#57]
Hello the issues is as follows:

Similar to recipes breaking when using an old Balm/cfb version, when Assembly Line Machines is used alongside Kubejs a server script from the latter causes many recipes to stop functioning.

I've tested with a profile containing only these two mods, as long as Kubejs doesn't use functions to remove recipes, ALM works fine, but as soon as Kubejs is used to remove a single recipe (from any mod or from vanilla), dusts become impossible to make and the pneumatic compressor loses many recipes.

[[issue on Kubejs's github]](https://github.com/KubeJS-Mods/KubeJS/issues/357#issue-1237578293)

**Comment by HaydenBelanger** [comment]
Hello! Please help me by providing me with an example KubeJS script to test with, and I will try to track it down and fix this issue from my end.

**Comment by LoSilopante** [comment]
Any server script that contains:
```
onEvent('recipes', event => {
  event.remove({output: 'minecraft:stonecutter'})
})
```
Note: 'minecraft:stonecutter' doesn't have to be an actual ID, no matter what you write there, even if you write 'test:test' and it makes the script not work, it will still break ALM's recipes.

**Comment by HaydenBelanger** [comment]
Alrighty, I will try to track this down.
