### ISSUE TITLE
Crash with custom recipes (KubeJS) 

### ISSUE THREAD

**Issue by Blatts12** [HaydenBelanger/assemblylinemachines#58]
I am working on a script that will unify resources in my modpack.

**Crash**

Steps:
1. Add recipes to, e.g. Pneumatic Compressor
2. Place the machine in the world
3. Crash

[Crash](https://gist.github.com/Blatts12/385e441efa26fb3c655b7913eddf516e)
[debug.log](https://gist.github.com/Blatts12/5d9792f66fc0e629d8e256964e80159a)

I have experimented with string as input:
['forge:nuggets/steel' crash](https://gist.github.com/Blatts12/ef5359a95cb105bf50e105bd09ac480a)
['#forge:nuggets/lumium' crash](https://gist.github.com/Blatts12/342dfb8a22e106653fc22ccf6adfacef)

**Script**

[Script](https://github.com/Blatts12/melo-s-modpack/blob/main/kubejs/server_scripts/unify/recipes/ALM.manager.js#L12)
Example of metal input, regarding the script:
[Create metal function](https://github.com/Blatts12/melo-s-modpack/blob/main/kubejs/server_scripts/unify/metals/Metal.js#L19)
[Example metal](https://github.com/Blatts12/melo-s-modpack/blob/main/kubejs/server_scripts/unify/metals/Basic.metal.js#L3)

How my script works:
1. Create `Metal` objects that contains required items and tags
2. Create `Recipe Managers` that alters recipes
3. Iterate over `metals` and `managers` to unify resources

**Comment by HaydenBelanger** [comment]
Hi! I've actually been working on a fix for a lot of the KubeJS issues in the background - look forward to a release very soon.

**Comment by HaydenBelanger** [comment]
Fixed as of the most recent version now available.
