### ISSUE TITLE
[1.18.2 Crash] Crash with ALM Machines?

### ISSUE THREAD

**Issue by itsdinkd** [HaydenBelanger/assemblylinemachines#59]
As title mentions, server is crashing due to ALM. When I /reload the server, server crashes.

https://pastebin.com/XQXuD3vj

**Comment by HaydenBelanger** [comment]
I'll be releasing an update to (hopefully) fix this as I can't reproduce it. It seems like an issue where your server is hanging unexpectedly, and I can't reproduce it on my side, but I will still be taking actions to try to prevent hanging in this case.

**Comment by itsdinkd** [comment]
There also seems to be an issue with... pretty much all the components missing their crafting recipe in the pneumatic compressor. Rods, gears, plates, nuggets have no recipes. I have everything turned on in the default common config. 

![image](https://user-images.githubusercontent.com/35115304/169939882-007482c2-cf4f-4ddf-bdb6-dbafab781b07.png)

![image](https://user-images.githubusercontent.com/35115304/169942364-e6019142-b821-4162-9da5-4e5d21d77847.png)

**Comment by itsdinkd** [comment]
@HaydenBelanger confirming to see if you saw the above comment, thanks
