### ISSUE TITLE
1.16.5 Book is given on every log in

### ISSUE THREAD

**Issue by SumaniPardia** [HaydenBelanger/assemblylinemachines#61]
Every time a player loads into a world (either on a server or solo world) they are given another guide book.  Attached is the config file for the pack (changed to txt so I can upload it, original file is toml).  I noticed this on another 1.18.2 pack, but I didn't play it much and never checked the config.  This is on a custom mod pack, let me know if you want the mod list.
[assemblylinemachines-common.toml.txt](https://github.com/HaydenBelanger/assemblylinemachines/files/8794225/assemblylinemachines-common.toml.txt)

**Comment by HaydenBelanger** [comment]
This issue is fixed in recent 1.18.2 versions and this fix will not be backported to 1.16.5 at this time.
