### ISSUE TITLE
[1.18.2] JEI is still missing tons of recipes

### ISSUE THREAD

**Issue by itsdinkd** [HaydenBelanger/assemblylinemachines#62]
JEI for some reason is no longer showing any category recipe for ALM. Nothing for purifier, nothing for compressor, nothing for alloy smelter, its all gone. Whats weird is that it sometimes shows, and then sometimes doesn't show. 

![image](https://user-images.githubusercontent.com/35115304/172960861-4fcffb3c-513b-4f2c-99b3-d8a9aaac8a2b.png)
![image](https://user-images.githubusercontent.com/35115304/172960892-6a1c73dc-fc0e-49e5-8c30-2ff431b73fbc.png)

not showing any recipes at all for plates (most likely due to JEI not showing the purifier/smelter recipes).

**Comment by itsdinkd** [comment]
Looking at the file JEI uses to place recipe categories, are these correct for assembly line?

![image](https://user-images.githubusercontent.com/35115304/172963266-821bfb72-96f7-4697-bb2b-ac9a8464fd7b.png)

**Comment by HaydenBelanger** [comment]
Those are the correct recipe categories, what version of JEI are you using?

**Comment by itsdinkd** [comment]
> 

always the latest. also if it helps, the recipes usually go missing when you are on a server.

Also if it helps, it works perfect with REI.

**Comment by HaydenBelanger** [comment]
May be system issue for you at this point - I was getting a HEAVY amount of reports of JEI issues until I put out a comprehensive fix and all was fixed, and I cannot reproduce on server or client.

If REI is working, I might suggest you move to there anyway - as a personal opinion REI is more stable lately, especially on servers.
