### ISSUE TITLE
JEI loses ALM tabs after world reload (/reload or leaving and rejoining world)

### ISSUE THREAD

**Issue by rovenfaded** [HaydenBelanger/assemblylinemachines#64]
Minecraft: 1.18.2
Forge: 40.1.51
ALM: assemblylinemachines-1.18.2-1.4.4.jar
JEI: jei-1.18.2-9.7.0.209.jar

When starting up minecraft and joining a world, everything is fine. However, after using /reload or leaving the world and rejoining a new world/the same world, JEI will no longer show ALM machine tabs (recipes from other things like crafting table and furnace are still visible). The recipes themselves do still work, but simply are no longer visible. The only way to fix is to restart the game.

Steps to reproduce:
1: Enter world
2: Check JEI for recipes
3: Type /reload
4: After reload is complete, check recipes again
5: ALM machine recipes are now no longer visible

**Comment by HaydenBelanger** [comment]
This has been fixed in 1.18.2-1.4.4.1 and 1.19-1.4.6.
