### ISSUE TITLE
Rendering overlay crash on startup

### ISSUE THREAD

**Issue by Enterprise12nx01** [HaydenBelanger/assemblylinemachines#65]
when adding this mod in 1.16.5 with electrodynamics and nuclear science(which launch and work fine until adding this mod)
the game crashes to desktop while launching the game.

Log: https://zerobin.net/?7f58302aeff47d4a#tg2YnkZ/YEZ0/Bz2dq3DbYLFqxpBzgcTacWvi7EzLX0=

**Comment by HaydenBelanger** [comment]
This is an issue caused by Nuclear Science where their Capsules are not prepared to handle the gaslike fluids in this mod which do not have physical properties. Please forward this log to their Github.

**Comment by Enterprise12nx01** [comment]
unfortunately they wont support anything but one version it seems, sadly 1.16 isnt supported and left a mess
