### ISSUE TITLE
Crash on Load Report

### ISSUE THREAD

**Issue by Tobanyi** [HaydenBelanger/assemblylinemachines#69]
https://pastebin.com/utKTrms9

**Comment by aAndrew3030** [comment]
Mod is not working with recent versions of forge due to breaking changes forge implemented. Best bet to get the mod working is to use a earlier version of forge until the mod dev updates to a recent version

**Comment by aAndrew3030** [comment]
forge 41.0.63 is the version you would want to use until a update is released

**Comment by HaydenBelanger** [comment]
Hello, this has been fixed as of the latest version.
