### ISSUE TITLE
Steel ingots aqm3

### ISSUE THREAD

**Issue by shel2015** [HaydenBelanger/assemblylinemachines#70]
*Please make sure to include a log, if the bug is related to a crash.* not crashing but I'm using almost a stack of iron have made not a single steel ingot. I use ground coac ground charcoal. Every time I get invalid recipe and to drain basin. Are you suppose to be trying that many times I'm wasting a huge amount of iron.

**Comment by HaydenBelanger** [comment]
Hello, this is an issue where the pack author chose to disable Steel being made within our implements. Try using another method of getting Steel in that pack.

**Comment by shel2015** [comment]
Thnkx

**Comment by shel2015** [comment]
Is there  a way to re-enable stee making. Why add a modpack if you're going to disable progression.

**Comment by HaydenBelanger** [comment]
Speak to the developer of AQM3, perhaps he will be able to re-enable it. As for that I think it's disabled through KubeJS and so editing some of the scripts should allow the recipe to be re-enabled.
