### ISSUE TITLE
Kinetic Grinder

### ISSUE THREAD

**Issue by Legoman848** [HaydenBelanger/assemblylinemachines#72]
Whenever I place a Kinetic grinder it crashes my game

**Comment by HaydenBelanger** [comment]
What version are you using, do you have a crash report log to give, and are you using any other mods?

**Comment by cmpashak** [comment]
@HaydenBelanger 
I am seeing this too. It also crashes when I open up (I believe) the page in the guide book for this item. 
MC version: 1.19.2
Forge: 43.0.8
Mod version: 1.4.10

Here is the crash for placing - https://pastebin.pl/view/899589f4

**Comment by HaydenBelanger** [comment]
@cmpashak I will work on this and get back to you!

**Comment by HaydenBelanger** [comment]
This issue has been fixed as of the latest version 1.4.11!
