### ISSUE TITLE
Industrial Foregoing and Create bug

### ISSUE THREAD

**Issue by Rimusp** [HaydenBelanger/assemblylinemachines#73]
If i install this mod together with Industrial foregoing and Create some create recipes (mechanical crafter for example) wont show in jei.
Ther is no crash but i found this error in the Log: https://pastebin.com/Lr0eYTjW
i have posted this on their site aswell as i dont know whose fault this really is.
Also using newest version on 1.18.2 of all mods

**Comment by HaydenBelanger** [comment]
From my side it looks like a Create issue. They're not prepared to handle a fluid which does not have a flowing fluid (a new option in semi-recent versions of Forge 1.18.2), which this mod's gases are.
