### ISSUE TITLE
Entropy Reactor

### ISSUE THREAD

**Issue by nin8995** [HaydenBelanger/assemblylinemachines#75]
*Please make sure to include a log, if the bug is related to a crash.*
[crash-2022-08-26_05.30.33-server.txt](https://github.com/HaydenBelanger/assemblylinemachines/files/9428092/crash-2022-08-26_05.30.33-server.txt)
Providing corrupted items to an entropy reactor, waiting a while, then crashed.

**Comment by HaydenBelanger** [comment]
This issue has been fixed in ther latest release 1.4.11!
