### ISSUE TITLE
Crash when viewing Ethane in JEI

### ISSUE THREAD

**Issue by AcrylicEater** [HaydenBelanger/assemblylinemachines#81]
Hey, so as i was viewing the uses for Ethane in JEI, my game crashed. This was reproducible and happened everytime i tried to do it.

The error description was "Getting tooltips" and the error specifically was
java.lang.NullPointerException: Cannot invoke "java.util.function.Supplier.get()" because "this.flowing" is null

Full crash log is appended here
https://pastebin.com/jpjUwuMw

**Comment by HaydenBelanger** [comment]
It's no longer easily possible with Fluid changes for me to display my gaslike fluids in JEI, so this is "fixed" by removing them from JEI.
