### ISSUE TITLE
Error loading the book

### ISSUE THREAD

**Issue by Akroten** [HaydenBelanger/assemblylinemachines#82]
Dear author of the mod, an error of the following kind: when receiving a book after the creation of the world, the book gives an error in trying to download 4 chapters, which is why access to the book is closed.
![2022-10-29_20 06 12](https://user-images.githubusercontent.com/90216287/199748221-e9a2edf0-6065-4170-9829-faedc97552d0.png)

**Comment by HaydenBelanger** [comment]
Fixed in latest versions already.
