### ISSUE TITLE
Cannot connect to server 1.18.2

### ISSUE THREAD

**Issue by oguh43** [HaydenBelanger/assemblylinemachines#84]
Beware. This mod will make you not able to join your server. Replacing jei with rei as suggested by the creator does noting. If your mod is the only one experiencing this behaviour, maybe its not a "jei issue for a while" but you are doing something wrong.
Stay away at all costs or do 50 backups.

**Comment by EndangeredNayla** [comment]
Still a bug

**Comment by oguh43** [comment]
> Still a bug

Can be "fixed" by installing a server side mod, which allows for longer login connection timeouts. Recommend 5 minutes.

**Comment by HaydenBelanger** [comment]
> > Still a bug
> 
> Can be "fixed" by installing a server side mod, which allows for longer login connection timeouts. Recommend 5 minutes.

For now this is the recommended fix while we figure out the cause of the issue. https://www.curseforge.com/minecraft/mc-mods/timeoutfixes

**Comment by oguh43** [comment]
Keep open for visibility or pin?
