### ISSUE TITLE
cant craft attuned titanium

### ISSUE THREAD

**Issue by RobinVanTol** [HaydenBelanger/assemblylinemachines#86]
![image](https://user-images.githubusercontent.com/38659478/222260374-acd225ed-6166-4926-9789-0a9f457a28ee.png)

the machine works for other recipes, i used it to make the pure titanium ingot, but cant turn the pure titanium into attuned titanium.

forge version 43.2.0
alm version 1.4.11

**Comment by Enterprise12nx01** [comment]
idk what im missing but i cannot make it either, i need the mk 2 purifier but it needs attuned titanium which is made in the mk 2??
