### ISSUE TITLE
Suspected incompatibility with JEI

### ISSUE THREAD

**Issue by zeroCNM** [HaydenBelanger/assemblylinemachines#89]
When I used this module with kubejs, create, and kubejs to write the recipe for the power mixer in version 1.18.2, I found that when I wrote or deleted the recipe for the power mixer, all the recipes for the power mixer would always disappear in Jei after reload. Only by deleting Jei's configuration file would it return to normal. After I checked it all, I found that the problem was caused by this module.

There were no errors of any kind throughout the entire process

Assembly Line Machines version is 1.4.4.3

The version of kubejs is kubejs forge 1802.5.5 build. 56

The kubejs create version is kubejs create forge 1802.2.2 build. 28

The create version is 0.5.0. i

Jei version is 10.2.1.1004

**Comment by HaydenBelanger** [comment]
I think this will be fixed in the latest version because I was registering my Recipe Types incorrectly, but I don't know KubeJS so I can't test it for now. I'm marking as closed and then if this is still an issue please let me know

**Comment by zeroCNM** [comment]
Sorry, I have identified the problem as an error in one of the dependencies of Kubejs, which resulted in incompatibility between Jei and Kubejs. However, due to the long history and lack of time for development due to personal reasons, I have forgotten which module has the specific issue. Recently, I have planned to go back and continue developing my integration package. If I find or think of any module issues, I will inform you promptly.
